# Generated by Django 4.2.7 on 2025-09-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='securityevent',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
