[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:$PORT"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100

[cron.daily-tasks]
schedule = "0 21 * * *"
command = "python manage.py send_daily_tasks"

[services.postgres]
type = "postgresql"
