[build]
builder = "nixpacks"

[deploy]
startCommand = "python railway_startup.py"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100

[cron.daily-tasks]
schedule = "0 21 * * *"
command = "python manage.py send_daily_tasks"

[services.postgres]
type = "postgresql"
