# Generated by Django 4.2.7 on 2025-11-21 18:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization name', max_length=200, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Organization description')),
                ('contact_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the organization is active')),
                ('is_trial', models.BooleanField(default=False, help_text='Whether organization is on trial')),
                ('trial_expires_at', models.DateTimeField(blank=True, help_text='Trial expiration date', null=True)),
                ('subscription_tier', models.CharField(choices=[('trial', 'Trial'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='trial', help_text='Subscription tier', max_length=50)),
                ('subscription_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', help_text='Subscription status', max_length=20)),
                ('max_farms', models.IntegerField(default=10, help_text='Maximum number of farms')),
                ('max_users', models.IntegerField(default=5, help_text='Maximum number of users')),
                ('max_houses_per_farm', models.IntegerField(default=20, help_text='Maximum houses per farm')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organizations/logos/')),
                ('primary_color', models.CharField(default='#1976d2', help_text='Primary brand color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#dc004e', help_text='Secondary brand color (hex)', max_length=7)),
                ('custom_domain', models.CharField(blank=True, help_text='Custom domain for white-labeling', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Administrator'), ('manager', 'Manager'), ('worker', 'Worker'), ('viewer', 'Viewer')], default='worker', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('can_manage_farms', models.BooleanField(default=False, help_text='Can create/edit/delete farms')),
                ('can_manage_users', models.BooleanField(default=False, help_text='Can manage organization users')),
                ('can_view_reports', models.BooleanField(default=True, help_text='Can view reports')),
                ('can_export_data', models.BooleanField(default=False, help_text='Can export data')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_users', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization User',
                'verbose_name_plural': 'Organization Users',
                'ordering': ['organization', 'user'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_b4dcc5_idx'), models.Index(fields=['user', 'is_active'], name='organizatio_user_id_a5c591_idx')],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_048085_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['subscription_status'], name='organizatio_subscri_999534_idx'),
        ),
    ]
