# Generated by Django 4.2.7 on 2026-06-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_mortalityrecord'),
        ('organizations', '0002_organizationinvite'),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Machine ID, e.g. send_report', max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('webhook_url', models.URLField(help_text='n8n production webhook URL', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Optional secret sent as X-Webhook-Secret header', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, help_text='Optional farm-specific workflow override', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_workflows', to='farms.farm')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_workflows', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='integration_organiz_2e3501_idx'), models.Index(fields=['slug'], name='integration_slug_1a7c80_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='automationworkflow',
            constraint=models.UniqueConstraint(fields=('organization', 'slug', 'farm'), name='unique_automation_workflow_per_org_slug_farm'),
        ),
    ]
