# Generated by Django 4.2.7 on 2025-11-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='KPI name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kpi_type', models.CharField(choices=[('flock_performance', 'Flock Performance'), ('farm_efficiency', 'Farm Efficiency'), ('cost_management', 'Cost Management'), ('growth', 'Growth'), ('health', 'Health'), ('productivity', 'Productivity'), ('custom', 'Custom')], help_text='Type of KPI', max_length=50)),
                ('metric_type', models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('average', 'Average'), ('percentage', 'Percentage'), ('ratio', 'Ratio'), ('trend', 'Trend'), ('comparison', 'Comparison')], help_text='Metric calculation type', max_length=20)),
                ('calculation_config', models.JSONField(default=dict, help_text='KPI calculation configuration (formula, data source, filters)')),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement (e.g., %, kg, days)', max_length=50)),
                ('target_value', models.FloatField(blank=True, help_text='Target value for this KPI', null=True)),
                ('warning_threshold', models.FloatField(blank=True, help_text='Warning threshold (below/above this triggers warning)', null=True)),
                ('critical_threshold', models.FloatField(blank=True, help_text='Critical threshold (below/above this triggers critical alert)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether KPI is available to all organization users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kpis', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['kpi_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Dashboard name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('dashboard_type', models.CharField(choices=[('executive', 'Executive Dashboard'), ('operational', 'Operational Dashboard'), ('farm', 'Farm Dashboard'), ('house', 'House Dashboard'), ('flock', 'Flock Dashboard'), ('custom', 'Custom Dashboard')], help_text='Type of dashboard', max_length=50)),
                ('layout_config', models.JSONField(default=dict, help_text='Dashboard layout configuration (widgets, positions, sizes)')),
                ('default_filters', models.JSONField(default=dict, help_text='Default filters (date range, farm, house, etc.)')),
                ('is_public', models.BooleanField(default=False, help_text='Whether dashboard is available to all organization users')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this dashboard belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Benchmark name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('benchmark_type', models.CharField(choices=[('industry', 'Industry Benchmark'), ('organization', 'Organization Benchmark'), ('farm', 'Farm Benchmark'), ('breed', 'Breed Benchmark'), ('custom', 'Custom Benchmark')], help_text='Type of benchmark', max_length=50)),
                ('metric_name', models.CharField(help_text='Metric name (e.g., FCR, Mortality Rate)', max_length=200)),
                ('average_value', models.FloatField(help_text='Average benchmark value')),
                ('min_value', models.FloatField(blank=True, help_text='Minimum benchmark value', null=True)),
                ('max_value', models.FloatField(blank=True, help_text='Maximum benchmark value', null=True)),
                ('percentile_25', models.FloatField(blank=True, help_text='25th percentile', null=True)),
                ('percentile_75', models.FloatField(blank=True, help_text='75th percentile', null=True)),
                ('unit', models.CharField(blank=True, help_text='Unit of measurement', max_length=50)),
                ('period_start', models.DateField(blank=True, help_text='Period start date', null=True)),
                ('period_end', models.DateField(blank=True, help_text='Period end date', null=True)),
                ('filters', models.JSONField(default=dict, help_text='Filters applied (breed, region, farm type, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_benchmarks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benchmarks', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Benchmark',
                'verbose_name_plural': 'Benchmarks',
                'ordering': ['benchmark_type', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Query name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('query_config', models.JSONField(default=dict, help_text='Query configuration (metrics, dimensions, filters, aggregations)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_queries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_queries', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Analytics Query',
                'verbose_name_plural': 'Analytics Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPICalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Calculated KPI value')),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('calculation_date', models.DateField(help_text='Date this calculation is for')),
                ('calculation_period_start', models.DateField(blank=True, help_text='Start of calculation period', null=True)),
                ('calculation_period_end', models.DateField(blank=True, help_text='End of calculation period', null=True)),
                ('filters', models.JSONField(default=dict, help_text='Filters applied during calculation (farm, house, flock, etc.)')),
                ('previous_value', models.FloatField(blank=True, help_text='Previous period value for comparison', null=True)),
                ('change_percentage', models.FloatField(blank=True, help_text='Percentage change from previous period', null=True)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('critical', 'Critical')], default='normal', help_text='Status based on thresholds', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_calculations', to=settings.AUTH_USER_MODEL)),
                ('kpi', models.ForeignKey(help_text='KPI this calculation belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='analytics.kpi')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kpi_calculations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'KPI Calculation',
                'verbose_name_plural': 'KPI Calculations',
                'ordering': ['-calculation_date', 'kpi'],
                'indexes': [models.Index(fields=['kpi', '-calculation_date'], name='analytics_k_kpi_id_65fd41_idx'), models.Index(fields=['organization', '-calculation_date'], name='analytics_k_organiz_3d4282_idx'), models.Index(fields=['status', '-calculation_date'], name='analytics_k_status_f564d3_idx')],
                'unique_together': {('kpi', 'calculation_date', 'organization', 'filters')},
            },
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['kpi_type', 'is_active'], name='analytics_k_kpi_typ_df8c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['organization', 'is_active'], name='analytics_k_organiz_5d6355_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['dashboard_type', 'is_active'], name='analytics_d_dashboa_e11e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['organization', 'is_active'], name='analytics_d_organiz_8f1128_idx'),
        ),
        migrations.AddIndex(
            model_name='benchmark',
            index=models.Index(fields=['benchmark_type', 'metric_name'], name='analytics_b_benchma_92e317_idx'),
        ),
        migrations.AddIndex(
            model_name='benchmark',
            index=models.Index(fields=['organization', 'is_active'], name='analytics_b_organiz_6f5595_idx'),
        ),
    ]
