# Generated by Django 4.2.7 on 2026-04-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_mortalityrecord'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='farm',
            field=models.ForeignKey(
                blank=True,
                help_text='Farm this dashboard belongs to',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='analytics_dashboards',
                to='farms.farm',
            ),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['farm', 'is_active'], name='analytics_d_farm_id_c66b26_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(
                condition=models.Q(dashboard_type='farm', farm__isnull=False),
                fields=('organization', 'farm', 'dashboard_type'),
                name='uniq_farm_dashboard_per_org',
            ),
        ),
    ]
