# Generated by Django 4.2.7 on 2025-09-20 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('farms', '0002_alter_farm_options_alter_farm_contact_email_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recurringtask',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['day_offset', 'task_name']},
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringtask',
            name='time',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AlterField(
            model_name='task',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='general', max_length=50),
        ),
        migrations.CreateModel(
            name='EmailTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField(default=django.utils.timezone.now)),
                ('sent_time', models.TimeField(default=django.utils.timezone.now)),
                ('recipients', models.JSONField(help_text='List of email addresses that received the notification')),
                ('subject', models.CharField(max_length=200)),
                ('houses_included', models.JSONField(help_text='List of house IDs included in the email')),
                ('tasks_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.farm')),
            ],
            options={
                'ordering': ['-sent_date', '-sent_time'],
                'unique_together': {('farm', 'sent_date')},
            },
        ),
    ]
