# Generated by Django 4.2.7 on 2025-11-29 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_mark_past_tasks_completed'),
        ('houses', '0005_controlsettings_device_houseconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('health', 'Bird Health'), ('environment', 'Environmental'), ('maintenance', 'Maintenance'), ('other', 'Other')], help_text='Category of the issue', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the issue', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the issue', max_length=20)),
                ('title', models.CharField(help_text='Brief title describing the issue', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('location_in_house', models.CharField(blank=True, help_text="Specific location within the house (e.g., 'Near feeder line 3')", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the issue was resolved')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User assigned to resolve the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('created_task', models.ForeignKey(blank=True, help_text='Task created from this issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_issues', to='tasks.task')),
                ('house', models.ForeignKey(help_text='House where the issue occurred', on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='houses.house')),
                ('reported_by', models.ForeignKey(help_text='User who reported the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, help_text='User who resolved the issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue',
                'verbose_name_plural': 'Issues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IssuePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', models.URLField(help_text='URL of the image on Cloudinary')),
                ('cloudinary_public_id', models.CharField(help_text='Cloudinary public ID for the image', max_length=255)),
                ('caption', models.CharField(blank=True, help_text='Optional caption for the photo', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(help_text='Issue this photo is attached to', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='issues.issue')),
                ('uploaded_by', models.ForeignKey(blank=True, help_text='User who uploaded the photo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Photo',
                'verbose_name_plural': 'Issue Photos',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IssueComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(help_text='Issue this comment belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
                ('user', models.ForeignKey(help_text='User who made the comment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Issue Comment',
                'verbose_name_plural': 'Issue Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['house', '-created_at'], name='issues_issu_house_i_03fde5_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status', '-created_at'], name='issues_issu_status_6ee1cb_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['category', '-created_at'], name='issues_issu_categor_2467a8_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority', '-created_at'], name='issues_issu_priorit_04bb52_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['reported_by', '-created_at'], name='issues_issu_reporte_11a799_idx'),
        ),
    ]
