# Generated by Django 4.2.7 on 2025-09-27 19:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('model_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('training_data_size', models.IntegerField(blank=True, null=True)),
                ('last_trained', models.DateTimeField(blank=True, null=True)),
                ('model_file_path', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ML Model',
                'verbose_name_plural': 'ML Models',
            },
        ),
        migrations.CreateModel(
            name='RotemFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(max_length=100, unique=True)),
                ('farm_name', models.CharField(max_length=200)),
                ('gateway_name', models.CharField(max_length=100)),
                ('gateway_alias', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rotem Farm',
                'verbose_name_plural': 'Rotem Farms',
            },
        ),
        migrations.CreateModel(
            name='RotemScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrape_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('data_points_collected', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rotem Scrape Log',
                'verbose_name_plural': 'Rotem Scrape Logs',
            },
        ),
        migrations.CreateModel(
            name='RotemUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=200)),
                ('display_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('is_farm_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rotem User',
                'verbose_name_plural': 'Rotem Users',
            },
        ),
        migrations.CreateModel(
            name='RotemController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_id', models.CharField(max_length=100, unique=True)),
                ('controller_name', models.CharField(max_length=200)),
                ('controller_type', models.CharField(max_length=50)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controllers', to='rotem_scraper.rotemfarm')),
            ],
            options={
                'verbose_name': 'Rotem Controller',
                'verbose_name_plural': 'Rotem Controllers',
            },
        ),
        migrations.CreateModel(
            name='MLPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_type', models.CharField(choices=[('anomaly', 'Anomaly Detection'), ('failure', 'Equipment Failure'), ('optimization', 'Environmental Optimization')], max_length=50)),
                ('predicted_at', models.DateTimeField()),
                ('confidence_score', models.FloatField()),
                ('prediction_data', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='rotem_scraper.rotemcontroller')),
            ],
            options={
                'verbose_name': 'ML Prediction',
                'verbose_name_plural': 'ML Predictions',
            },
        ),
        migrations.CreateModel(
            name='RotemDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('data_type', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('quality', models.CharField(default='good', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='rotem_scraper.rotemcontroller')),
            ],
            options={
                'verbose_name': 'Rotem Data Point',
                'verbose_name_plural': 'Rotem Data Points',
                'indexes': [models.Index(fields=['controller', 'timestamp'], name='rotem_scrap_control_ec68f7_idx'), models.Index(fields=['data_type', 'timestamp'], name='rotem_scrap_data_ty_50dab9_idx')],
                'unique_together': {('controller', 'timestamp', 'data_type')},
            },
        ),
    ]
