# Generated by Django 4.2.7 on 2025-09-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotem_scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotemfarm',
            name='rotem_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='rotemfarm',
            name='rotem_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
