# Generated by Django 4.2.7 on 2025-09-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rotem_scraper', '0002_rotemfarm_rotem_password_rotemfarm_rotem_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotemdatapoint',
            name='high_alarm_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotemdatapoint',
            name='low_alarm_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rotemdatapoint',
            name='target_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
