# Generated by Django 4.2.7 on 2025-11-29 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotem_scraper', '0003_rotemdatapoint_high_alarm_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotemDailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_avg', models.FloatField(blank=True, null=True)),
                ('temperature_min', models.FloatField(blank=True, null=True)),
                ('temperature_max', models.FloatField(blank=True, null=True)),
                ('temperature_data_points', models.IntegerField(default=0)),
                ('humidity_avg', models.FloatField(blank=True, null=True)),
                ('humidity_min', models.FloatField(blank=True, null=True)),
                ('humidity_max', models.FloatField(blank=True, null=True)),
                ('humidity_data_points', models.IntegerField(default=0)),
                ('static_pressure_avg', models.FloatField(blank=True, null=True)),
                ('static_pressure_min', models.FloatField(blank=True, null=True)),
                ('static_pressure_max', models.FloatField(blank=True, null=True)),
                ('static_pressure_data_points', models.IntegerField(default=0)),
                ('wind_speed_avg', models.FloatField(blank=True, null=True)),
                ('wind_speed_min', models.FloatField(blank=True, null=True)),
                ('wind_speed_max', models.FloatField(blank=True, null=True)),
                ('wind_speed_data_points', models.IntegerField(default=0)),
                ('water_consumption_avg', models.FloatField(blank=True, null=True)),
                ('water_consumption_min', models.FloatField(blank=True, null=True)),
                ('water_consumption_max', models.FloatField(blank=True, null=True)),
                ('water_consumption_data_points', models.IntegerField(default=0)),
                ('feed_consumption_avg', models.FloatField(blank=True, null=True)),
                ('feed_consumption_min', models.FloatField(blank=True, null=True)),
                ('feed_consumption_max', models.FloatField(blank=True, null=True)),
                ('feed_consumption_data_points', models.IntegerField(default=0)),
                ('anomalies_count', models.IntegerField(default=0)),
                ('warnings_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('total_data_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='rotem_scraper.rotemcontroller')),
            ],
            options={
                'verbose_name': 'Rotem Daily Summary',
                'verbose_name_plural': 'Rotem Daily Summaries',
                'ordering': ['-date', 'controller'],
                'indexes': [models.Index(fields=['controller', 'date'], name='rotem_scrap_control_2025c5_idx'), models.Index(fields=['date'], name='rotem_scrap_date_e13026_idx'), models.Index(fields=['controller', '-date'], name='rotem_scrap_control_544327_idx')],
                'unique_together': {('controller', 'date')},
            },
        ),
    ]
