# Generated by Django 4.2.7 on 2025-09-20 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.IntegerField()),
                ('chicken_in_date', models.DateField()),
                ('chicken_out_date', models.DateField(blank=True, null=True)),
                ('chicken_out_day', models.IntegerField(default=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='farms.farm')),
            ],
            options={
                'ordering': ['farm', 'house_number'],
                'unique_together': {('farm', 'house_number')},
            },
        ),
    ]
