# Generated by Django 4.2.7 on 2025-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='batch_start_date',
            field=models.DateField(blank=True, help_text='Date when current batch started', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='capacity',
            field=models.IntegerField(default=1000, help_text='Maximum chicken capacity'),
        ),
        migrations.AddField(
            model_name='house',
            name='current_age_days',
            field=models.IntegerField(default=0, help_text='Current chicken age in days'),
        ),
        migrations.AddField(
            model_name='house',
            name='expected_harvest_date',
            field=models.DateField(blank=True, help_text='Expected harvest date', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='is_integrated',
            field=models.BooleanField(default=False, help_text='Whether this house is integrated with external system'),
        ),
        migrations.AddField(
            model_name='house',
            name='last_system_sync',
            field=models.DateTimeField(blank=True, help_text='Last sync with external system', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='system_house_id',
            field=models.CharField(blank=True, help_text='External system house ID', max_length=100, null=True),
        ),
    ]
