# Generated by Django 4.2.7 on 2025-11-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_add_monitoring_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='housealarm',
            new_name='houses_hous_house_i_7af7a4_idx',
            old_name='houses_hous_house_a_idx',
        ),
        migrations.RenameIndex(
            model_name='housealarm',
            new_name='houses_hous_is_acti_6a2f0f_idx',
            old_name='houses_hous_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='housealarm',
            new_name='houses_hous_severit_29f5fb_idx',
            old_name='houses_hous_severit_idx',
        ),
        migrations.RenameIndex(
            model_name='housemonitoringsnapshot',
            new_name='houses_hous_house_i_fd3ee1_idx',
            old_name='houses_hous_house_t_idx',
        ),
        migrations.RenameIndex(
            model_name='housemonitoringsnapshot',
            new_name='houses_hous_timesta_6fa1d9_idx',
            old_name='houses_hous_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='housemonitoringsnapshot',
            new_name='houses_hous_house_i_a11812_idx',
            old_name='houses_hous_house_i_alarm_idx',
        ),
    ]
