# Generated by Django 4.2.7 on 2025-11-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_rename_houses_hous_house_a_idx_houses_hous_house_i_7af7a4_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_curve', models.JSONField(default=dict, help_text='Day-based temperature targets {day: temperature}')),
                ('min_temperature', models.FloatField(blank=True, help_text='Minimum temperature (F)', null=True)),
                ('max_temperature', models.FloatField(blank=True, help_text='Maximum temperature (F)', null=True)),
                ('target_temperature', models.FloatField(blank=True, help_text='Current target temperature (F)', null=True)),
                ('temperature_offset', models.FloatField(default=0.0, help_text='Temperature offset adjustment')),
                ('humidity_target', models.FloatField(blank=True, help_text='Target humidity percentage', null=True)),
                ('humidity_treatment_enabled', models.BooleanField(default=False)),
                ('humidity_min', models.FloatField(blank=True, null=True)),
                ('humidity_max', models.FloatField(blank=True, null=True)),
                ('co2_target', models.FloatField(blank=True, help_text='Target CO2 level (ppm)', null=True)),
                ('co2_treatment_enabled', models.BooleanField(default=False)),
                ('co2_max', models.FloatField(blank=True, null=True)),
                ('ventilation_mode', models.CharField(choices=[('minimum', 'Minimum Ventilation'), ('tunnel', 'Tunnel Ventilation'), ('natural', 'Natural Ventilation'), ('mixed', 'Mixed Mode')], default='minimum', max_length=50)),
                ('static_pressure_target', models.FloatField(blank=True, help_text='Target static pressure', null=True)),
                ('static_pressure_min', models.FloatField(blank=True, null=True)),
                ('static_pressure_max', models.FloatField(blank=True, null=True)),
                ('lighting_schedule', models.JSONField(default=dict, help_text='Lighting schedule configuration')),
                ('light_dimmer_level', models.FloatField(blank=True, help_text='Light dimmer percentage (0-100)', null=True)),
                ('cooling_pad_enabled', models.BooleanField(default=False)),
                ('cooling_pad_threshold', models.FloatField(blank=True, null=True)),
                ('fogger_enabled', models.BooleanField(default=False)),
                ('fogger_threshold', models.FloatField(blank=True, null=True)),
                ('water_on_demand_enabled', models.BooleanField(default=True)),
                ('feed_schedule', models.JSONField(default=dict, help_text='Feed schedule configuration')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='control_settings', to='houses.house')),
            ],
            options={
                'verbose_name': 'Control Settings',
                'verbose_name_plural': 'Control Settings',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('heater', 'Heater'), ('tunnel_fan', 'Tunnel Fan'), ('exhaust_fan', 'Exhaust Fan'), ('stir_fan', 'Stir Fan'), ('cooling_pad', 'Cooling Pad'), ('light', 'Light'), ('feeder', 'Feeder'), ('auger', 'Auger'), ('water_system', 'Water System'), ('ventilation', 'Ventilation'), ('other', 'Other')], max_length=50)),
                ('device_number', models.IntegerField(help_text='Device number/identifier within the house')),
                ('name', models.CharField(blank=True, help_text='Optional device name', max_length=200)),
                ('status', models.CharField(choices=[('on', 'On'), ('off', 'Off'), ('error', 'Error'), ('maintenance', 'Maintenance')], default='off', max_length=20)),
                ('percentage', models.FloatField(blank=True, help_text='Percentage/level (0-100) for variable devices', null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='houses.house')),
            ],
            options={
                'ordering': ['house', 'device_type', 'device_number'],
            },
        ),
        migrations.CreateModel(
            name='HouseConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_feet', models.FloatField(blank=True, help_text='House length in feet', null=True)),
                ('width_feet', models.FloatField(blank=True, help_text='House width in feet', null=True)),
                ('height_feet', models.FloatField(blank=True, help_text='House height in feet', null=True)),
                ('total_square_feet', models.FloatField(blank=True, help_text='Total square footage', null=True)),
                ('sensor_layout', models.JSONField(default=dict, help_text='Sensor positions and types')),
                ('relay_layout', models.JSONField(default=dict, help_text='Relay assignments and configurations')),
                ('fan_air_capacity_cfm', models.FloatField(blank=True, help_text='Total fan air capacity in CFM', null=True)),
                ('tunnel_fan_count', models.IntegerField(default=0)),
                ('exhaust_fan_count', models.IntegerField(default=0)),
                ('stir_fan_count', models.IntegerField(default=0)),
                ('scale_settings', models.JSONField(default=dict, help_text='Scale configuration')),
                ('silo_count', models.IntegerField(default=0)),
                ('auger_count', models.IntegerField(default=0)),
                ('feeder_count', models.IntegerField(default=0)),
                ('drinker_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='houses.house')),
            ],
            options={
                'verbose_name': 'House Configuration',
                'verbose_name_plural': 'House Configurations',
            },
        ),
        migrations.CreateModel(
            name='TemperatureCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day of flock (0-42)')),
                ('target_temperature', models.FloatField(help_text='Target temperature in Fahrenheit')),
                ('notes', models.TextField(blank=True)),
                ('control_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_curves', to='houses.controlsettings')),
            ],
            options={
                'ordering': ['day'],
                'unique_together': {('control_settings', 'day')},
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('pressure', 'Pressure'), ('co2', 'CO2'), ('ammonia', 'Ammonia'), ('wind_speed', 'Wind Speed'), ('wind_direction', 'Wind Direction'), ('water_meter', 'Water Meter'), ('feed_scale', 'Feed Scale'), ('bird_scale', 'Bird Scale'), ('other', 'Other')], max_length=50)),
                ('sensor_number', models.IntegerField(help_text='Sensor number/identifier')),
                ('location', models.CharField(blank=True, help_text='Sensor location description', max_length=200)),
                ('calibration_data', models.JSONField(default=dict, help_text='Calibration parameters')),
                ('last_calibration', models.DateTimeField(blank=True, null=True)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='houses.house')),
            ],
            options={
                'ordering': ['house', 'sensor_type', 'sensor_number'],
                'unique_together': {('house', 'sensor_type', 'sensor_number')},
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='houses.device')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='houses_devi_device__deb6bb_idx'), models.Index(fields=['timestamp'], name='houses_devi_timesta_12ac64_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['house', 'device_type'], name='houses_devi_house_i_13de78_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='houses_devi_status_128094_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together={('house', 'device_type', 'device_number')},
        ),
    ]
