# Generated by Django 4.2.7 on 2025-12-01 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0008_mortalityrecord'),
        ('houses', '0005_controlsettings_device_houseconfiguration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterConsumptionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateField(help_text='Date when the abnormal consumption was detected')),
                ('growth_day', models.IntegerField(blank=True, help_text='Growth day when alert occurred', null=True)),
                ('current_consumption', models.FloatField(help_text='Current water consumption (L/day)')),
                ('baseline_consumption', models.FloatField(help_text='Baseline/average consumption (L/day)')),
                ('increase_percentage', models.FloatField(help_text='Percentage increase from baseline')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField(help_text='Alert message describing the anomaly')),
                ('detection_method', models.CharField(default='statistical', help_text='Method used to detect anomaly (statistical, threshold, ml)', max_length=50)),
                ('is_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_recipients', models.JSONField(default=list, help_text='List of email addresses that received the alert')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_water_alerts', to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_alerts', to='farms.farm')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_alerts', to='houses.house')),
            ],
            options={
                'verbose_name': 'Water Consumption Alert',
                'verbose_name_plural': 'Water Consumption Alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['house', '-created_at'], name='houses_wate_house_i_961518_idx'), models.Index(fields=['farm', '-created_at'], name='houses_wate_farm_id_d58ce2_idx'), models.Index(fields=['is_acknowledged', '-created_at'], name='houses_wate_is_ackn_5c9aa4_idx'), models.Index(fields=['severity', '-created_at'], name='houses_wate_severit_dd7528_idx'), models.Index(fields=['alert_date', '-created_at'], name='houses_wate_alert_d_72691f_idx')],
                'unique_together': {('house', 'alert_date')},
            },
        ),
    ]
