# Generated by Django 4.2.7 on 2025-12-01 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_waterconsumptionalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterconsumptionalert',
            name='expected_consumption',
            field=models.FloatField(blank=True, help_text='Age-adjusted expected consumption (L/day) based on growth day and bird count', null=True),
        ),
    ]
