# Generated by Django 4.2.7 on 2026-04-22 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_mortalityrecord'),
        ('houses', '0009_water_alert_lifecycle_and_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmMonitoringCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_payload', models.JSONField(default=dict)),
                ('comparison_payload', models.JSONField(default=dict)),
                ('houses_payload', models.JSONField(default=dict)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('refresh_state', models.CharField(choices=[('idle', 'Idle'), ('refreshing', 'Refreshing'), ('failed', 'Failed'), ('fresh', 'Fresh')], default='idle', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseMonitoringCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_payload', models.JSONField(default=dict)),
                ('history_payload', models.JSONField(default=dict)),
                ('kpis_payload', models.JSONField(default=dict)),
                ('heater_payload', models.JSONField(default=dict)),
                ('source_timestamp', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('refresh_state', models.CharField(choices=[('idle', 'Idle'), ('refreshing', 'Refreshing'), ('failed', 'Failed'), ('fresh', 'Fresh')], default='idle', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameIndex(
            model_name='waterconsumptionforecast',
            new_name='houses_wate_house_i_61acfd_idx',
            old_name='houses_water_house_id_8dd4cb_idx',
        ),
        migrations.RenameIndex(
            model_name='waterconsumptionforecast',
            new_name='houses_wate_farm_id_a4e089_idx',
            old_name='houses_water_farm_id_890ff2_idx',
        ),
        migrations.RenameIndex(
            model_name='waterconsumptionforecast',
            new_name='houses_wate_horizon_dcee83_idx',
            old_name='houses_water_horizon_8bc54f_idx',
        ),
        migrations.AddField(
            model_name='housemonitoringcache',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_cache', to='houses.house'),
        ),
        migrations.AddField(
            model_name='farmmonitoringcache',
            name='farm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_cache', to='farms.farm'),
        ),
        migrations.AddIndex(
            model_name='housemonitoringcache',
            index=models.Index(fields=['fetched_at'], name='houses_hous_fetched_64d43e_idx'),
        ),
        migrations.AddIndex(
            model_name='housemonitoringcache',
            index=models.Index(fields=['refresh_state'], name='houses_hous_refresh_877902_idx'),
        ),
        migrations.AddIndex(
            model_name='farmmonitoringcache',
            index=models.Index(fields=['fetched_at'], name='houses_farm_fetched_ae82bf_idx'),
        ),
        migrations.AddIndex(
            model_name='farmmonitoringcache',
            index=models.Index(fields=['refresh_state'], name='houses_farm_refresh_53b1fd_idx'),
        ),
    ]
