# Generated by Django 4.2.7 on 2025-11-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Template description')),
                ('report_type', models.CharField(choices=[('flock_performance', 'Flock Performance'), ('farm_summary', 'Farm Summary'), ('house_status', 'House Status'), ('task_completion', 'Task Completion'), ('financial', 'Financial'), ('custom', 'Custom')], help_text='Type of report', max_length=50)),
                ('template_config', models.JSONField(default=dict, help_text='Report template configuration (filters, fields, formatting)')),
                ('data_source', models.JSONField(default=dict, help_text='Data source configuration (models, fields, filters)')),
                ('default_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', help_text='Default export format', max_length=20)),
                ('include_charts', models.BooleanField(default=True, help_text='Include charts/graphs in report')),
                ('include_summary', models.BooleanField(default=True, help_text='Include summary section')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=False, help_text='Whether template is available to all organizations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_report_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this template belongs to (null for global templates)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Scheduled report name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], help_text='Report frequency', max_length=20)),
                ('schedule_config', models.JSONField(default=dict, help_text='Schedule configuration (day of week, day of month, time, etc.)')),
                ('email_recipients', models.JSONField(default=list, help_text='Additional email recipients (list of email addresses)')),
                ('report_filters', models.JSONField(default=dict, help_text='Filters to apply to each report (date range, farm, house, etc.)')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', help_text='Schedule status', max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, help_text='Next scheduled run time', null=True)),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Last run time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='organizations.organization')),
                ('recipients', models.ManyToManyField(help_text='Users who will receive this report', related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(help_text='Report template to use', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reporting.reporttemplate')),
            ],
            options={
                'verbose_name': 'Scheduled Report',
                'verbose_name_plural': 'Scheduled Reports',
                'ordering': ['next_run_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Execution status', max_length=20)),
                ('parameters', models.JSONField(default=dict, help_text='Report parameters (filters, date range, etc.)')),
                ('report_file', models.FileField(blank=True, help_text='Generated report file', null=True, upload_to='reports/')),
                ('export_format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel (XLSX)'), ('csv', 'CSV'), ('json', 'JSON'), ('html', 'HTML')], default='pdf', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('execution_time_seconds', models.FloatField(blank=True, help_text='Report generation time in seconds', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_executions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_executions', to='organizations.organization')),
                ('scheduled_report', models.ForeignKey(blank=True, help_text='Scheduled report that triggered this execution', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reporting.scheduledreport')),
                ('template', models.ForeignKey(help_text='Report template used', on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='reporting.reporttemplate')),
            ],
            options={
                'verbose_name': 'Report Execution',
                'verbose_name_plural': 'Report Executions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportBuilderQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Query name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('query_config', models.JSONField(default=dict, help_text='Query configuration (models, fields, filters, aggregations)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_queries', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_queries', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Report Builder Query',
                'verbose_name_plural': 'Report Builder Queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['status', 'next_run_at'], name='reporting_s_status_013f2f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledreport',
            index=models.Index(fields=['organization', 'status'], name='reporting_s_organiz_451697_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type', 'is_active'], name='reporting_r_report__a12015_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['organization', 'is_active'], name='reporting_r_organiz_1ae597_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['status', '-started_at'], name='reporting_r_status_8bb27f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['scheduled_report', '-started_at'], name='reporting_r_schedul_358dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='reportexecution',
            index=models.Index(fields=['organization', '-started_at'], name='reporting_r_organiz_cfb3cf_idx'),
        ),
    ]
