# Generated by Django 4.2.7 on 2025-09-20 03:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={},
        ),
        migrations.AlterField(
            model_name='farm',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='farm',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(blank=True, help_text='e.g., Manager, Supervisor, Worker', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('receive_daily_tasks', models.BooleanField(default=True, help_text='Receive daily task reminders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='farms.farm')),
            ],
            options={
                'unique_together': {('farm', 'email')},
            },
        ),
    ]
