# Generated by Django 4.2.7 on 2025-09-22 10:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_farm_options_alter_farm_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of this task program')),
                ('duration_days', models.PositiveIntegerField(default=40, help_text='Total duration of the program in days', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default program for new farms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms', to='farms.program'),
        ),
        migrations.CreateModel(
            name='ProgramTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='Day of the program when this task should be performed (-1 for setup day)', validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(365)])),
                ('task_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('one_time', 'One Time'), ('recurring', 'Recurring')], default='daily', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the task')),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step instructions')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('estimated_duration', models.PositiveIntegerField(default=30, help_text='Estimated duration in minutes')),
                ('is_required', models.BooleanField(default=True, help_text='Is this task required or optional')),
                ('requires_confirmation', models.BooleanField(default=False, help_text='Requires worker confirmation')),
                ('recurring_days', models.JSONField(blank=True, default=list, help_text='For recurring tasks: list of days (0=Monday, 6=Sunday)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='farms.program')),
            ],
            options={
                'ordering': ['day', 'priority', 'title'],
                'unique_together': {('program', 'day', 'title')},
            },
        ),
    ]
