# Generated by Django 4.2.7 on 2025-09-22 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_program_farm_program_programtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('task_added', 'Task Added'), ('task_modified', 'Task Modified'), ('task_deleted', 'Task Deleted'), ('program_modified', 'Program Modified')], max_length=20)),
                ('change_description', models.TextField()),
                ('old_data', models.JSONField(blank=True, help_text='Previous state of the changed item', null=True)),
                ('new_data', models.JSONField(blank=True, help_text='New state of the changed item', null=True)),
                ('user_choice', models.CharField(blank=True, choices=[('retroactive', 'Apply to Current Flock'), ('next_flock', 'Apply to Next Flock')], help_text="User's choice for handling existing farm tasks", max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('affected_farms', models.ManyToManyField(blank=True, related_name='program_changes', to='farms.farm')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='farms.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
