# Generated by Django 4.2.7 on 2025-09-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_programchangelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the farm'),
        ),
        migrations.AddField(
            model_name='farm',
            name='has_system_integration',
            field=models.BooleanField(default=False, help_text='Whether this farm has system integration'),
        ),
        migrations.AddField(
            model_name='farm',
            name='integration_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('not_configured', 'Not Configured')], default='not_configured', help_text='Current status of the integration', max_length=20),
        ),
        migrations.AddField(
            model_name='farm',
            name='integration_type',
            field=models.CharField(choices=[('none', 'No Integration'), ('rotem', 'Rotem System'), ('future_system', 'Future System')], default='none', help_text='Type of system integration', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='last_sync',
            field=models.DateTimeField(blank=True, help_text='Last successful data sync', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='rotem_farm_id',
            field=models.CharField(blank=True, help_text='Rotem system farm ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='rotem_gateway_alias',
            field=models.CharField(blank=True, help_text='Rotem gateway alias', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='rotem_gateway_name',
            field=models.CharField(blank=True, help_text='Rotem gateway name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='rotem_password',
            field=models.CharField(blank=True, help_text='Rotem system password', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='rotem_username',
            field=models.CharField(blank=True, help_text='Rotem system username', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='location',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
