# Generated by Django 4.2.7 on 2025-11-21 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0004_rename_houses_hous_house_a_idx_houses_hous_house_i_7af7a4_idx_and_more'),
        ('farms', '0005_farm_description_farm_has_system_integration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Breed name (e.g., Cobb 500, Ross 308)', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Breed code/identifier', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Breed description and characteristics')),
                ('average_weight_gain_per_week', models.FloatField(blank=True, help_text='Average weight gain per week in grams', null=True)),
                ('average_feed_conversion_ratio', models.FloatField(blank=True, help_text='Average FCR (Feed Conversion Ratio)', null=True)),
                ('average_mortality_rate', models.FloatField(blank=True, help_text='Average mortality rate as percentage (0-100)', null=True)),
                ('typical_harvest_age_days', models.IntegerField(blank=True, help_text='Typical harvest age in days', null=True)),
                ('typical_harvest_weight_grams', models.FloatField(blank=True, help_text='Typical harvest weight in grams', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='Batch/flock number', max_length=100)),
                ('flock_code', models.CharField(help_text='Unique flock identifier code', max_length=100, unique=True)),
                ('arrival_date', models.DateField(help_text='Date chickens arrived at the house')),
                ('expected_harvest_date', models.DateField(blank=True, help_text='Expected harvest date', null=True)),
                ('actual_harvest_date', models.DateField(blank=True, help_text='Actual harvest date', null=True)),
                ('start_date', models.DateField(blank=True, help_text='Flock start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Flock end date', null=True)),
                ('initial_chicken_count', models.IntegerField(help_text='Initial number of chickens placed')),
                ('current_chicken_count', models.IntegerField(blank=True, help_text='Current number of chickens (updated over time)', null=True)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('arrival', 'Arrival'), ('growing', 'Growing'), ('production', 'Production'), ('harvesting', 'Harvesting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='setup', help_text='Current flock status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this flock is currently active')),
                ('supplier', models.CharField(blank=True, help_text='Chicken supplier name', max_length=200)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this flock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breed', models.ForeignKey(blank=True, help_text='Breed of chickens in this flock', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flocks', to='farms.breed')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_flocks', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(help_text='House where this flock is located', on_delete=django.db.models.deletion.CASCADE, related_name='flocks', to='houses.house')),
            ],
            options={
                'verbose_name': 'Flock',
                'verbose_name_plural': 'Flocks',
                'ordering': ['-arrival_date', 'batch_number'],
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization this farm belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='organizations.organization'),
        ),
        migrations.CreateModel(
            name='FlockPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='Date of this performance record')),
                ('flock_age_days', models.IntegerField(help_text='Flock age in days at record date')),
                ('average_weight_grams', models.FloatField(blank=True, help_text='Average weight per chicken in grams', null=True)),
                ('total_weight_kg', models.FloatField(blank=True, help_text='Total flock weight in kg', null=True)),
                ('feed_consumed_kg', models.FloatField(blank=True, help_text='Total feed consumed in kg (cumulative or for period)', null=True)),
                ('daily_feed_consumption_kg', models.FloatField(blank=True, help_text='Daily feed consumption in kg', null=True)),
                ('feed_conversion_ratio', models.FloatField(blank=True, help_text='Feed Conversion Ratio (FCR)', null=True)),
                ('daily_water_consumption_liters', models.FloatField(blank=True, help_text='Daily water consumption in liters', null=True)),
                ('current_chicken_count', models.IntegerField(help_text='Current number of chickens')),
                ('mortality_count', models.IntegerField(default=0, help_text='Number of deaths (cumulative or for period)')),
                ('mortality_rate', models.FloatField(blank=True, help_text='Mortality rate as percentage', null=True)),
                ('livability', models.FloatField(blank=True, help_text='Livability percentage', null=True)),
                ('average_temperature', models.FloatField(blank=True, null=True)),
                ('average_humidity', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes for this record')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(help_text='Flock this performance record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='farms.flock')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_flock_performance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flock Performance',
                'verbose_name_plural': 'Flock Performance Records',
                'ordering': ['flock', 'record_date', 'flock_age_days'],
            },
        ),
        migrations.CreateModel(
            name='FlockComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Comparison name', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('comparison_metrics', models.JSONField(default=list, help_text="List of metrics to compare (e.g., ['fcr', 'mortality_rate', 'weight_gain'])")),
                ('comparison_results', models.JSONField(blank=True, help_text='Cached comparison results', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flock_comparisons', to=settings.AUTH_USER_MODEL)),
                ('flocks', models.ManyToManyField(help_text='Flocks included in this comparison', related_name='comparisons', to='farms.flock')),
            ],
            options={
                'verbose_name': 'Flock Comparison',
                'verbose_name_plural': 'Flock Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['code'], name='farms_breed_code_ed4bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='breed',
            index=models.Index(fields=['is_active'], name='farms_breed_is_acti_692a0c_idx'),
        ),
        migrations.AddIndex(
            model_name='flockperformance',
            index=models.Index(fields=['flock', '-record_date'], name='farms_flock_flock_i_52e0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='flockperformance',
            index=models.Index(fields=['flock', 'flock_age_days'], name='farms_flock_flock_i_032e48_idx'),
        ),
        migrations.AddIndex(
            model_name='flockperformance',
            index=models.Index(fields=['record_date'], name='farms_flock_record__bd26d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flockperformance',
            unique_together={('flock', 'record_date', 'flock_age_days')},
        ),
        migrations.AddIndex(
            model_name='flock',
            index=models.Index(fields=['flock_code'], name='farms_flock_flock_c_9a0847_idx'),
        ),
        migrations.AddIndex(
            model_name='flock',
            index=models.Index(fields=['house', '-arrival_date'], name='farms_flock_house_i_611001_idx'),
        ),
        migrations.AddIndex(
            model_name='flock',
            index=models.Index(fields=['status', 'is_active'], name='farms_flock_status_29a9e5_idx'),
        ),
        migrations.AddIndex(
            model_name='flock',
            index=models.Index(fields=['breed', '-arrival_date'], name='farms_flock_breed_i_51d23b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='flock',
            unique_together={('house', 'batch_number')},
        ),
    ]
