# Generated by Django 4.2.7 on 2025-11-21 18:02

from django.conf import settings
from django.db import migrations
import uuid


def create_default_organization_and_assign_farms(apps, schema_editor):
    """Create default organization and assign existing farms to it"""
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationUser = apps.get_model('organizations', 'OrganizationUser')
    Farm = apps.get_model('farms', 'Farm')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    
    # Get or create default organization
    default_org, created = Organization.objects.get_or_create(
        slug='default',
        defaults={
            'id': uuid.uuid4(),
            'name': 'Default Organization',
            'description': 'Default organization for existing farms',
            'contact_email': 'admin@example.com',
            'is_active': True,
            'is_trial': False,
            'subscription_tier': 'standard',
            'subscription_status': 'active',
            'max_farms': 1000,
            'max_users': 1000,
            'max_houses_per_farm': 100,
        }
    )
    
    if created:
        print(f"✅ Created default organization: {default_org.name}")
    else:
        print(f"ℹ️  Using existing default organization: {default_org.name}")
    
    # Assign all farms without organization to default organization
    farms_without_org = Farm.objects.filter(organization__isnull=True)
    count = farms_without_org.update(organization_id=default_org.id)
    
    if count > 0:
        print(f"✅ Assigned {count} farm(s) to default organization")
    else:
        print("ℹ️  No farms needed assignment")
    
    # Create OrganizationUser for each existing user
    users = User.objects.all()
    org_users_created = 0
    
    for user in users:
        org_user, created = OrganizationUser.objects.get_or_create(
            organization=default_org,
            user=user,
            defaults={
                'role': 'owner' if user.is_staff else 'worker',
                'is_active': True,
                'can_manage_farms': user.is_staff,
                'can_manage_users': user.is_staff,
                'can_view_reports': True,
                'can_export_data': user.is_staff,
            }
        )
        if created:
            org_users_created += 1
    
    if org_users_created > 0:
        print(f"✅ Created {org_users_created} organization user membership(s)")
    else:
        print("ℹ️  All users already have organization memberships")


def reverse_assign_farms(apps, schema_editor):
    """Reverse migration - remove organization assignment"""
    Organization = apps.get_model('organizations', 'Organization')
    OrganizationUser = apps.get_model('organizations', 'OrganizationUser')
    Farm = apps.get_model('farms', 'Farm')
    
    # Set organization to None for farms in default organization
    default_org = Organization.objects.filter(slug='default').first()
    if default_org:
        Farm.objects.filter(organization=default_org).update(organization=None)
        
        # Optionally delete default organization and its users
        # Uncomment if you want to clean up:
        # OrganizationUser.objects.filter(organization=default_org).delete()
        # default_org.delete()
        print("⚠️  Removed organization assignments (default organization not deleted)")


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0006_breed_flock_farm_organization_flockperformance_and_more'),
    ]

    operations = [
        migrations.RunPython(
            create_default_organization_and_assign_farms,
            reverse_assign_farms
        ),
    ]
