# Generated by Django 4.2.7 on 2025-11-29 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('houses', '0005_controlsettings_device_houseconfiguration_and_more'),
        ('farms', '0007_assign_farms_to_default_org'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortalityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='Date of mortality recording')),
                ('total_deaths', models.IntegerField(help_text='Total number of deaths')),
                ('disease_deaths', models.IntegerField(default=0, help_text='Deaths due to disease')),
                ('culling_deaths', models.IntegerField(default=0, help_text='Deaths due to culling')),
                ('accident_deaths', models.IntegerField(default=0, help_text='Deaths due to accidents')),
                ('heat_stress_deaths', models.IntegerField(default=0, help_text='Deaths due to heat stress')),
                ('cold_stress_deaths', models.IntegerField(default=0, help_text='Deaths due to cold stress')),
                ('unknown_deaths', models.IntegerField(default=0, help_text='Deaths from unknown causes')),
                ('other_deaths', models.IntegerField(default=0, help_text='Deaths from other causes')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the mortality')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(help_text='Flock this mortality record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='farms.flock')),
                ('house', models.ForeignKey(help_text='House where mortality occurred', on_delete=django.db.models.deletion.CASCADE, related_name='mortality_records', to='houses.house')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this mortality', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_mortalities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mortality Record',
                'verbose_name_plural': 'Mortality Records',
                'ordering': ['-record_date', '-created_at'],
                'indexes': [models.Index(fields=['flock', '-record_date'], name='farms_morta_flock_i_dc02b7_idx'), models.Index(fields=['house', '-record_date'], name='farms_morta_house_i_313955_idx'), models.Index(fields=['-record_date'], name='farms_morta_record__651263_idx')],
                'unique_together': {('flock', 'record_date')},
            },
        ),
    ]
